default_language_version:
  python: python3.7

default_stages: [commit, push]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer

  - repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: flake8
        types: [python]
        language: python

  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: isort
        args:
          - '--diff'
          - '--check-only'
          - '.'
        types: [python]
        language: python

  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        args:
          - '--diff'
          - '--check'
          - '--config'
          - 'pyproject.toml'
          - '.'
        types: [python]
        language: python
