[build-system]
requires = ["setuptools>=51.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.black]
target-version = ["py37"]
line-length = 120
color = true

extend-exclude = '''
.git
.mypy_cache
.tox
dist
venv
'''
